@baseUrl = http://localhost:8000

@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZTliNDBjYi0wNDYyLTRlMzMtOTQzZC1lZDFiNDMwNDY0MTIiLCJwZXJmaXMiOlsiQWRtaW5pc3RyYWRvciJdLCJleHAiOjE3Nzc1MDUzNTd9.hnhITVpzJEnHkjcXf3_UMn0xgruAjBfF1SALFSwZhBA

@tokenAtendente = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MDBjZjQ1MC1jYWM5LTRkNzUtYjYxNC01MDhjMDk4NmFkZWMiLCJwZXJmaXMiOlsiQXRlbmRlbnRlIl0sImV4cCI6MTc3NzUwNTQ2M30.XdM_Jmml5-EPhPbeaiDxgT2wi9r-uQuOpMZU2POVxQo


@tokenUsuario = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNWMxZmZlOS0xOTE5LTRiNGItODVmNi0zNWUxYmM5ZjA2MjQiLCJwZXJmaXMiOlsiTWVjYW5pY28iXSwiZXhwIjoxNzc3MjM0NjExfQ.YBg6vXpLJ9LUgobSlphcHHzNUBEFY_TLVYYH0KMhFA0
## Sequencia de testes
## Sobe container com seed populado, 1 usuario com perfil administrador criado

### Criar usuário (sem autenticação - deve falhar)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json

{
    "nome": "Francisco da silva 3",
    "email": "francisco.povoasSilva3@example.com",
    "senha": "senha123"
}


### Listar todos
## Tokean obtido para o usuario admin criado no seed
##  token obtido em auth.http
GET {{baseUrl}}/api/v1/usuarios HTTP/1.1
Authorization: Bearer {{tokenAdmin}}


### Filtrar por id
# aqui retorna o perfil do usuario.
GET {{baseUrl}}/api/v1/usuarios/400cf450-cac9-4d75-b614-508c0986adec HTTP/1.1
Authorization: Bearer {{tokenAdmin}}


### Criar usuário (com autenticação - deve conseguir)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "nome": "Francisco Povoas",
    "email": "francisco.povoasSilva3@example.com",
    "senha": "senha123",
    "perfis": ["Atendente"]
}

### Criar usuário (com autenticação - deve conseguir)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "nome": "Carlos Silva",
    "email": "carlos.silva@example.com",
    "senha": "senha123",
    "perfis": ["Mecanico"]
}

### Criar usuário (com autenticação - deve conseguir)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "nome": "Francisco Mecanico",
    "email": "francisco.mecanico@example.com",
    "senha": "senha123",
    "perfis": ["Mecanico"]
}

### Filtrar por nome
GET {{baseUrl}}/api/v1/usuarios?nome=Francisco%20Povoas HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Filtrar por email
GET {{baseUrl}}/api/v1/usuarios?email=francisco.povoas@example.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Filtrar por ativo
GET {{baseUrl}}/api/v1/usuarios?ativo=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Deletar usuário
DELETE {{baseUrl}}/api/v1/usuarios/e3a1ec71-5871-4e20-a1ce-f4feb4658e4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###
GET {{baseUrl}}/api/v1/usuarios?ativo=true HTTP/1.1

### Atualizar email do usuário
PATCH {{baseUrl}}/api/v1/usuarios/d0f2d8d2-d7d0-4cf1-9676-38b399360c24 HTTP/1.1
Content-Type: application/json

{
    "email": "francisco.povoas@example.com"
}