@baseUrl = http://localhost:8000
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYWE3OTZlZi03YzhjLTQyM2UtODkxOC1kYmViYWNhNjE0ODAiLCJwZXJmaXMiOlsiQWRtaW5pc3RyYWRvciJdLCJleHAiOjE3NzcyMzM5OTN9.csSyLRyDAmC1Y5EB6ToG0pxyEjxj6xSgMu0SqacxE30
@tokenUsuario = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNWMxZmZlOS0xOTE5LTRiNGItODVmNi0zNWUxYmM5ZjA2MjQiLCJwZXJmaXMiOlsiTWVjYW5pY28iXSwiZXhwIjoxNzc3MjM0NjExfQ.YBg6vXpLJ9LUgobSlphcHHzNUBEFY_TLVYYH0KMhFA0
## Sequencia de testes
## Sobe container com seed populado, 1 usuario com perfil administrador criado

### Criar usuário (sem autenticação - deve falhar)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json

{
    "nome": "Francisco da silva 3",
    "email": "francisco.povoasSilva3@example.com",
    "senha": "senha123"
}


### Listar todos
## Tokean obtido para o usuario admin criado no seed
##  token obtido em auth.http
GET {{baseUrl}}/api/v1/usuarios HTTP/1.1
Authorization: Bearer {{tokenAdmin}}


### Filtrar por id
# aqui retorna o perfil do usuario.
GET {{baseUrl}}/api/v1/usuarios/1d613b21-5190-428f-944f-d0f1fb7fb133 HTTP/1.1
Authorization: Bearer {{tokenAdmin}}


### Criar usuário (com autenticação - deve conseguir)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "nome": "Francisco Povoas",
    "email": "francisco.povoasSilva3@example.com",
    "senha": "senha123",
    "perfis": ["Administrador", "Atendente"]
}

### Criar usuário (com autenticação - deve conseguir)
POST {{baseUrl}}/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "nome": "Francisco Mecanico",
    "email": "francisco.mecanico@example.com",
    "senha": "senha123",
    "perfis": ["Mecanico"]
}

### Filtrar por nome
GET {{baseUrl}}/api/v1/usuarios?nome=Francisco%20Povoas HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Filtrar por email
GET {{baseUrl}}/api/v1/usuarios?email=francisco.povoas@example.com HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Filtrar por ativo
GET {{baseUrl}}/api/v1/usuarios?ativo=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenUsuario}}

### Deletar usuário
DELETE {{baseUrl}}/api/v1/usuarios/1dc84ff0-543e-406d-b6a4-5ce01e86c2e6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

###
GET {{baseUrl}}/api/v1/usuarios?ativo=true HTTP/1.1

### Atualizar email do usuário
PATCH {{baseUrl}}/api/v1/usuarios/d0f2d8d2-d7d0-4cf1-9676-38b399360c24 HTTP/1.1
Content-Type: application/json

{
    "email": "francisco.povoas@example.com"
}