"""add criado_em, ativo e atualizado_em to usuario

Revision ID: 0c780fb2a15b
Revises: 20260419_01
Create Date: 2026-04-21 20:07:44.207002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0c780fb2a15b'
down_revision: Union[str, Sequence[str], None] = '20260419_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('criado_em', sa.DateTime(), nullable=False))
    op.add_column('usuario', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    op.add_column('usuario', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'ativo')
    op.drop_column('usuario', 'atualizado_em')
    op.drop_column('usuario', 'criado_em')
    # ### end Alembic commands ###
