"""create estoque table

Revision ID: 19b45f99e858
Revises: fb7d6128017c
Create Date: 2026-05-01 17:12:54.670490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '19b45f99e858'
down_revision: Union[str, Sequence[str], None] = 'fb7d6128017c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_estoque',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('quantidade_reservada', sa.Integer(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic
    op.drop_table('item_estoque')
    # ### end Alembic commands ###
