"""create OrdemServicoModel, OrdemServicoServicoModel, OrdemServicoItemModel

Revision ID: 52bbdccca29d
Revises: 19b45f99e858
Create Date: 2026-05-02 20:14:54.613303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '52bbdccca29d'
down_revision: Union[str, Sequence[str], None] = '19b45f99e858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('veiculo_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('queixa_inicial', sa.Text(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('iniciado_diagnostico_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diagnostico_concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ordem_servico_id', sa.Uuid(), nullable=False),
    sa.Column('item_estoque_id', sa.Uuid(), nullable=False),
    sa.Column('nome_item', sa.String(length=100), nullable=False),
    sa.Column('tipo_item', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['item_estoque_id'], ['item_estoque.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_servico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ordem_servico_id', sa.Uuid(), nullable=False),
    sa.Column('servico_id', sa.Uuid(), nullable=False),
    sa.Column('nome_servico', sa.String(length=100), nullable=False),
    sa.Column('descricao_servico', sa.String(length=255), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tempo_estimado_minutos', sa.Integer(), nullable=False),
    sa.Column('tempo_executado_minutos', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['catalogo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic
    op.drop_table('ordem_servico_servico')
    op.drop_table('ordem_servico_item')
    op.drop_table('ordem_servico')
    # ### end Alembic commands ###
