"""criacao de tabela perfil e pivo usuario_perfil

Revision ID: 692e8bc96fc1
Revises: de518a81b957
Create Date: 2026-04-25 20:05:22.729696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.shared.value_objects.id import ID
from app.modules.iam.domain.entities.perfil import PerfilTipos
from datetime import datetime, UTC


# revision identifiers, used by Alembic.
revision: str = '692e8bc96fc1'
down_revision: Union[str, Sequence[str], None] = 'de518a81b957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario_perfil',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["perfil_id"], ["perfil.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'perfil_id', name='uix_usuario_perfil')
    )
    # ### end Alembic commands ###


    perfil_table = sa.table(
        "perfil",
        sa.column("id", sa.Uuid()),
        sa.column("nome", sa.String()),
        sa.column("descricao", sa.String()),
        sa.column("ativo", sa.Boolean()),
        sa.column("criado_em", sa.DateTime(timezone=True)),
        sa.column("atualizado_em", sa.DateTime(timezone=True)),
    )
    agora = datetime.now(UTC)
    op.bulk_insert(
        perfil_table,
        [
            {
                "id": ID.generate().value,
                "nome": PerfilTipos.ADMINISTRADOR.value,
                "descricao": "Administrador do sistema",
                "ativo": True,
                "criado_em": agora,
                "atualizado_em": agora,
            },
            {
                "id": ID.generate().value,
                "nome": PerfilTipos.ATENDENTE.value,
                "descricao": "Atendente",
                "ativo": True,
                "criado_em": agora,
                "atualizado_em": agora,
            },
            {
                "id": ID.generate().value,
                "nome": PerfilTipos.MECANICO.value,
                "descricao": "Mecanico",
                "ativo": True,
                "criado_em": agora,
                "atualizado_em": agora,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_perfil')
    op.drop_table('perfil')
    # ### end Alembic commands ###
