sonar.projectKey=Tech-challenge
sonar.projectName=Tech-challenge

sonar.sources=app

sonar.tests=tests/unit,tests/integration
sonar.test.inclusions=tests/unit/**/*.py,tests/integration/**/*.py

sonar.exclusions=tests/dev/**,.venv/**,venv/**,**/__pycache__/**,.pytest_cache/**,.git/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=reports/coverage-unit.xml,reports/coverage-integration.xml