apiVersion: v1
kind: Service
metadata:
  name: mvp-oficina-api-service
  namespace: staging
  labels:
    app: mvp-oficina-api
    environment: staging
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "189.4.123.56/32"
  selector:
    app: mvp-oficina-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000